/*
 * MainForm.java
 *
 * Created on __DATE__, __TIME__
 */

package forms;

import java.awt.event.ActionEvent;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import tools.InputHandler;
import tools.MiniConsole;

/**
 *
 * @author  __USER__
 */
public class MainForm extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static Logger logger = LogManager.getLogger(MainForm.class);

	/** Creates new form MainForm */
	public MainForm() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnConsole = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				formKeyPressed(evt);
			}
		});

		btnConsole.setText("MiniConsole");
		btnConsole.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConsoleActionPerformed(evt);
			}
		});

		jButton1.setText("\u4f60\u597d");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(btnConsole)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED, 165,
								Short.MAX_VALUE).add(jButton1).add(61, 61, 61)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(btnConsole).add(jButton1))
						.addContainerGap(261, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	protected void btnConsoleActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		logger.info("btnConsoleActionPerformed");
		final MiniConsole console = new MiniConsole("MiniConsoleTest");
		console.setInputHandler(new InputHandler() {

			public void onLineInput(String line) {
				// TODO Auto-generated method stub
				System.out.println(line);
				console.println(line);
			}
		});
		console.start();
	}

	private void formKeyPressed(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		logger.info("key " + evt.getKeyChar());
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnConsole;
	private javax.swing.JButton jButton1;
	// End of variables declaration//GEN-END:variables

}